version: '3.8'

services:
  api:
    build:
      dockerfile: ./api/Dockerfile.api
    ports:
      - "5000:5000"

  frontend:
    build:
      dockerfile: ./app/Dockerfile.frontend
    ports:
      - "3000:3000"
